---
# tasks file for sensu
- hosts: localhost
  connection: local
  tasks:
  - name: install ruby
    yum: name={{ item }} state=present
    with_items:
      - gcc-c++
      - patch
      - readline
      - readline-devel
      - zlib
      - zlib-devel
      - libffi-devel
      - openssl-devel
      - make
      - bzip2
      - autoconf
      - automake
      - libtool
      - bison
      - sqlite-devel
  - name: install RVM and Ruby
    script: /home/Sensu_Ansible_CF/sensu/tasks/file.sh 
